# Generated by Django 3.0.5 on 2020-05-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snackbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('snack_bar', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='snackbar.SnackBar')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('unlimited', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('max_per_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('picture', models.ImageField(default=None, null=True, upload_to='items')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Category')),
            ],
        ),
    ]
