# Generated by Django 3.0.5 on 2020-05-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='snack_bar',
        ),
    ]
