# Generated by Django 3.0.6 on 2020-05-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_ingredients_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredients_json',
        ),
    ]
