# Generated by Django 3.0.5 on 2020-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackbar',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
