# Generated by Django 3.0.6 on 2020-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
