# Generated by Django 3.0.6 on 2020-05-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_ingredients_json'),
        ('orders', '0002_auto_20200512_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=2)),
                ('special_instructions', models.TextField(blank=True, default=None)),
                ('name', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
            ],
        ),
    ]
