# Generated by Django 3.0.6 on 2020-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200513_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
